project: "DLC"
experimenter: "Poe"


# for image extraction
random_state: 42
num_frames_per_video: 25
extract_method: "phash"

# for training
optimizer: "AdamW"
n_epochs: 300
batch_size: 12
num_frames_for_train: 400 


paths:
  data: ../data
  labeling: ../data/labeling
  model: ../data/model
  evaluation: ../data/evaluation